<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <InvariantGlobalization>true</InvariantGlobalization>
        <NoDefaultLaunchSettingsFile>True</NoDefaultLaunchSettingsFile>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Aspire.Azure.Messaging.ServiceBus" Version="10.0.0" />
      <PackageReference Include="Aspire.Azure.Storage.Blobs" Version="10.0.0" />
      <PackageReference Include="Azure.Messaging.ServiceBus" Version="7.20.1" />
      <PackageReference Include="Azure.Storage.Blobs" Version="12.27.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\ServiceBusDeadLettersCleanup.ServiceDefaults\ServiceBusDeadLettersCleanup.ServiceDefaults.csproj" />
    </ItemGroup>

</Project>
