name: pulumi-docker-build

on:
  push:
    branches:
    - 'main'

jobs:
  build:
    uses: baoduy/ShareWorkflows/.github/workflows/docker-publish.yaml@main
    with:
      dockerFile: 'ServiceBusDeadLettersCleanup/Dockerfile'
      context: './ServiceBusDeadLettersCleanup'
      imageName: 'baoduy2412/servicebus-cleanup'
      platforms: linux/arm64,linux/amd64
    secrets:
      DOCKER_USERNAME: baoduy2412
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
